title: xuanhong_Pan's Homepage
page-top-title: xuanhong_Pan
top-section-bg-text: Be what you wanna be
home-subtitle: xuanhong_Pan&enfp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
